document.addEventListener("DOMContentLoaded",()=>{const $=id=>document.getElementById(id);const profileKey="storeScienceProfile";const subjects=[["⚛️","Physics","Your Physics study files"],["🧪","Chemistry","Your Chemistry study files"],["📐","Mathematics","Your Mathematics study files"],["💻","Computer Science","Your Computer Science study files"]];const site=$("site"),login=$("profileScreen"),profileModal=$("profileModal"),aiModal=$("modal"),grid=$("subjects"),home=$("homeSubjects"),subjectPage=$("subjectPage"),tools=document.querySelector(".tools");
function showLogin(){site.style.display="none";login.style.display="grid"}function showSite(){login.style.display="none";site.style.display="block"}
function avatar(g){const x=g==="female"?"👩🏻‍🎓":"👨🏻‍🎓";$("avatarFace").textContent=x;$("modalAvatar").textContent=x}
function stats(){$("fileTotal").textContent="0";$("mcqTotal").textContent="0";$("bestScore").textContent="—"}
function saveProfile(p){localStorage.setItem(profileKey,JSON.stringify(p));showSite();$("welcomeText").textContent="Welcome back, "+p.name+". Keep learning and keep growing.";avatar(p.gender);stats()}
function render(q=""){q=q.toLowerCase();grid.innerHTML=subjects.filter(s=>s.join(" ").toLowerCase().includes(q)).map(s=>'<article class="subject" data-subject="'+s[1]+'"><div class="emoji">'+s[0]+'</div><h4>'+s[1]+'</h4><p>'+s[2]+'</p><div class="arrow">→</div></article>').join("");$("count").textContent=grid.children.length+" subject"+(grid.children.length===1?"":"s");grid.querySelectorAll(".subject").forEach(el=>el.addEventListener("click",()=>openSubject(el.dataset.subject)))}
function openSubject(name){home.style.display="none";tools.style.display="none";subjectPage.style.display="block";$("subjectName").textContent=name}
function openProfile(){let p={};try{p=JSON.parse(localStorage.getItem(profileKey)||"{}")}catch(e){}$("detailName").textContent=p.name||"—";$("detailAge").textContent=p.age||"—";$("detailGender").textContent=p.gender==="female"?"Female":"Male";$("detailClass").textContent=p.studentClass==="12"?"Class 12":"Class 11";$("modalName").textContent=p.name||"Student";$("modalClass").textContent=p.studentClass==="12"?"Class 12":"Class 11";avatar(p.gender);profileModal.style.display="grid"}
const saved=localStorage.getItem(profileKey);if(saved){try{const p=JSON.parse(saved);showSite();$("welcomeText").textContent="Welcome back, "+p.name+".";avatar(p.gender)}catch(e){localStorage.removeItem(profileKey);showLogin()}}else showLogin();
$("startBtn").addEventListener("click",()=>{const p={name:$("profileName").value.trim(),age:$("profileAge").value,gender:$("profileGender").value,studentClass:$("profileClass").value};if(!p.name||!p.age||!p.gender||!p.studentClass){alert("Please complete all profile details.");return}saveProfile(p)});
$("profileBtn").addEventListener("click",openProfile);$("profileClose").addEventListener("click",()=>profileModal.style.display="none");profileModal.addEventListener("click",e=>{if(e.target===profileModal)profileModal.style.display="none"});
$("themeBtn").addEventListener("click",()=>{document.body.classList.toggle("dark");$("themeBtn").textContent=document.body.classList.contains("dark")?"☀":"☾"});
$("editProfile").addEventListener("click",()=>{const p=JSON.parse(localStorage.getItem(profileKey)||"{}");$("profileModal").style.display="none";$("profileName").value=p.name||"";$("profileAge").value=p.age||"";$("profileGender").value=p.gender||"";$("profileClass").value=p.studentClass||"";showLogin()});
$("logoutBtn").addEventListener("click",()=>{localStorage.removeItem(profileKey);profileModal.style.display="none";showLogin()});
$("search").addEventListener("input",e=>render(e.target.value));$("backBtn").addEventListener("click",()=>{subjectPage.style.display="none";home.style.display="block";tools.style.display="block";render()});
$("aiBtn").addEventListener("click",()=>aiModal.style.display="grid");$("close").addEventListener("click",()=>aiModal.style.display="none");aiModal.addEventListener("click",e=>{if(e.target===aiModal)aiModal.style.display="none"});
$("mcqBtn").addEventListener("click",()=>{const sub=$("mcqSubject").value;const qs={Physics:["Which law relates force, mass and acceleration?","What is the SI unit of work?","What does velocity measure?"],Chemistry:["What is atomic number?","Which particle has a negative charge?","What is Avogadro’s constant?"],Mathematics:["What is the domain of a function?","What is sin²θ+cos²θ?","What is a quadratic equation?"],"Computer Science":["What does CPU stand for?","What is an algorithm?","What is a variable?"]}[sub];$("mcqOutput").innerHTML='<div class="answer"><b>Practice set — '+sub+'</b><ol>'+Array.from({length:10},(_,i)=>"<li>"+qs[i%qs.length]+"</li>").join("")+"</ol></div>"});
render();stats();});